import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next.js CRUD App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col max-w-4xl mx-auto px-4 py-4">
        <div className="flex items-center gap-4">
          <Image
            src="/fruit.jpg"
            alt="Favourite fruit"
            width={100}
            height={100}
          />
          <h1 className="mb-4 text-4xl font-bold tracking-tight">
            Next.js CRUD App
          </h1>
        </div>
        <hr />
        <p>&nbsp;</p>
        {children}
        <p>&nbsp;</p>
        <hr />
        Created by J. B.
      </body>
    </html>
  );
}
